const cur=document.getElementById('cur'),curR=document.getElementById('curR');
let mx=0,my=0,rx=0,ry=0;
document.addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;cur.style.left=mx+'px';cur.style.top=my+'px';});
(function loop(){rx+=(mx-rx)*.1;ry+=(my-ry)*.1;curR.style.left=rx+'px';curR.style.top=ry+'px';requestAnimationFrame(loop);})();
(function(){const c=document.getElementById('phC');if(!c)return;const ctx=c.getContext('2d');let W,H;function resize(){W=c.width=c.offsetWidth;H=c.height=c.offsetHeight}resize();window.addEventListener('resize',resize);const bands=[{col:'#ff9500',yC:.2,amp:.09,fr:.003,sp:.35,n:12,spr:.05,ph:0},{col:'#4488ff',yC:.5,amp:.08,fr:.0055,sp:.55,n:10,spr:.045,ph:2.2},{col:'#00e5ff',yC:.8,amp:.07,fr:.0022,sp:.28,n:8,spr:.04,ph:4}];function wY(b,x,t,i){const off=(i/(b.n-1)-.5)*b.spr*H;return b.yC*H+(Math.sin(x*b.fr+t*b.sp+b.ph)+Math.sin(x*b.fr*1.65+t*b.sp*1.3+b.ph+.9)*.3)*b.amp*H+off;}let t=0;function draw(){ctx.fillStyle='rgba(0,0,5,.15)';ctx.fillRect(0,0,W,H);bands.forEach(b=>{for(let li=0;li<b.n;li++){const cf=1-Math.abs(li/(b.n-1)-.5)*2;ctx.beginPath();for(let s=0;s<=W;s+=2){const y=wY(b,s,t,li);s===0?ctx.moveTo(s,y):ctx.lineTo(s,y);}ctx.strokeStyle=b.col;ctx.globalAlpha=.07+.45*cf*cf;ctx.lineWidth=.5+cf*.9;ctx.shadowBlur=cf>.6?8:0;ctx.shadowColor=b.col;ctx.stroke();}});ctx.globalAlpha=1;ctx.shadowBlur=0;t+=.011;requestAnimationFrame(draw);}draw();})();
const PERSONAS=[
{id:"visionnaire",name:"Le Visionnaire",icon:"🔮",color:"#aa44ff",dominance:"Thêta",stable:"Thêta",wave:"theta",alpha:20,theta:72,beta:15,essence:"Vous percevez d'abord le sens et la direction d'ensemble, avant même que les détails ne prennent forme.",citation:"« L'imagination est plus importante que le savoir, car le savoir est limité, tandis que l'imagination englobe le monde entier. »",citationAuthor:"Albert Einstein",activite:"Le Visionnaire présente une dominance nette de l'onde Thêta, à la fois par son niveau de variation et par sa stabilité sur l'ensemble de la séance. Les ondes Thêta sont généralement associées à la pensée intuitive, à l'imagerie mentale, à la créativité et aux états de réflexion interne. Ce profil reflète un fonctionnement cérébral orienté vers l'intégration globale de l'information plutôt que vers un traitement analytique ou séquentiel.",perception:"La pensée du Visionnaire s'organise d'abord autour d'une vision d'ensemble. Lorsqu'une situation ou un projet émerge, la première perception concerne le sens global, la direction possible et la cohérence générale. Les détails et les étapes intermédiaires apparaissent dans un second temps. Ce mode de fonctionnement repose largement sur des représentations mentales, des images et des scénarios. Les idées prennent forme avant d'être formulées verbalement.",action:"Dans l'action, le Visionnaire excelle lorsqu'il s'agit d'imaginer, de projeter et de structurer une vision à long terme. Il est naturellement à l'aise avec les concepts fondateurs, les orientations stratégiques et les projets encore en gestation. Son approche privilégie la cohérence globale plutôt que l'optimisation immédiate.",conditions:"L'efficacité du Visionnaire est maximale dans des environnements calmes, où le rythme permet une réflexion intérieure soutenue. C'est dans ces contextes que les connexions mentales se renforcent et que la vision devient plus claire. La réflexion ne se force pas : elle émerge progressivement.",role:"Au sein d'un collectif, le Visionnaire occupe fréquemment un rôle de mise en perspective. Il contribue à définir une direction, à clarifier une intention ou à donner du sens à un projet. Il aide le groupe à se projeter au-delà de l'immédiat.",strengths:"Forte capacité de synthèse, intuition structurée et aptitude naturelle à penser l'évolution et la transformation. Créativité cohérente orientée vers le sens.",environments:"Contextes où la vision précède l'exécution. Innovation, stratégie, création, conception de projets porteurs de sens.",synthese:"Le Visionnaire incarne un fonctionnement cérébral orienté vers la projection, la cohérence et l'anticipation. Sa force principale réside dans sa capacité à donner forme à l'invisible et à inscrire l'action dans une vision globale.",compatible:["Le Médiateur","Le Pionnier","L'Observateur"],tension:["Le Décideur","Le Pilote"]},
{id:"mediateur",name:"Le Médiateur",icon:"🕊️",color:"#00ffcc",dominance:"Thêta",stable:"Alpha",wave:"theta",alpha:44,theta:58,beta:14,essence:"Vous captez intuitivement ce qui se joue et vous le transformez en compréhension claire, simple et apaisée.",citation:"« La simplicité est la sophistication suprême. »",citationAuthor:"Léonard de Vinci",activite:"Le Médiateur se caractérise par une dominance de l'onde Thêta, associée à une stabilité marquée de l'onde Alpha sur l'ensemble de la séance. Les ondes Thêta sont liées à l'intuition, à la sensibilité et à l'imagerie mentale, tandis que les ondes Alpha sont associées à un état de calme, de régulation émotionnelle et de clarté mentale.",perception:"La perception du Médiateur repose sur une sensibilité fine aux ambiances, aux émotions et aux dynamiques humaines. Les informations sont souvent ressenties avant d'être formulées. Ce profil capte rapidement ce qui se joue dans une situation, y compris ce qui n'est pas explicitement exprimé.",action:"Dans l'action, le Médiateur se distingue par sa capacité à simplifier sans appauvrir. Il rassemble plutôt qu'il ne disperse, clarifie plutôt qu'il ne complexifie.",conditions:"Le fonctionnement optimal du Médiateur apparaît dans des états de calme intérieur. Il donne le meilleur de lui-même dans des contextes qui laissent place à la présence, à l'écoute et à la réflexion posée.",role:"Au sein d'un collectif, le Médiateur joue un rôle de régulation et de clarification. Il écoute attentivement, reformule ce que les autres perçoivent confusément et aide à apaiser les tensions.",strengths:"Forte clarté intérieure, capacité naturelle à faire émerger l'essentiel à partir du flou. Intuition équilibrée par une stabilité émotionnelle.",environments:"Environnements où l'écoute est valorisée, la réflexion respectée, l'humain central. Accompagnement, enseignement, conseil, communication.",synthese:"Le Médiateur incarne un fonctionnement cérébral orienté vers la justesse et la clarté. Il transforme des ressentis subtils en compréhension structurée.",compatible:["Le Visionnaire","L'Observateur","Le Chef d'Orchestre"],tension:["Le Pionnier","L'Éclaireur"]},
{id:"pionnier",name:"Le Pionnier",icon:"🚀",color:"#ff9500",dominance:"Thêta",stable:"Bêta",wave:"theta",alpha:22,theta:62,beta:48,essence:"Vous transformez spontanément l'intuition en action et les idées en expériences concrètes.",citation:"« Le meilleur moyen de commencer, c'est d'arrêter de parler et de s'y mettre. »",citationAuthor:"Walt Disney",activite:"Le Pionnier présente une dominance nette de l'onde Thêta, ponctuée de pics Bêta lors de l'initiation de l'action. Les ondes Thêta reflètent l'imagination et la créativité, tandis que les pointes Bêta traduisent l'engagement et la concrétisation rapide des idées.",perception:"La pensée du Pionnier s'organise par essai et élan. Il perçoit d'abord les potentiels et les directions nouvelles, puis teste ces intuitions dans le réel. L'idée seule ne lui suffit pas : elle doit se confronter à l'expérience.",action:"Dans l'action, le Pionnier excelle lorsqu'il s'agit de donner forme à des visions encore naissantes. Il agit rapidement, prend des initiatives naturelles et utilise chaque essai pour renforcer son intuition.",conditions:"Ce profil performe dans des environnements ouverts et innovants, où l'expérimentation est possible et l'initiative valorisée.",role:"Dans une équipe, le Pionnier agit comme catalyseur et lanceur. Il initie les idées, ouvre de nouvelles voies et insuffle un dynamisme qui motive le groupe à passer de la réflexion à l'action.",strengths:"Capacité à transformer rapidement les idées en actions concrètes, dynamisme créatif, aptitude à initier des projets.",environments:"Contextes entrepreneuriaux, innovants ou créatifs. Startups, équipes de développement produit.",synthese:"Le Pionnier incarne un fonctionnement cérébral orienté vers la génération et la réalisation des possibles. Il transforme l'intuition en mouvement et les visions en réalités concrètes.",compatible:["Le Décideur","L'Éclaireur","Le Visionnaire"],tension:["Le Médiateur","Le Chef d'Orchestre"]},
{id:"decideur",name:"Le Décideur",icon:"⚡",color:"#4488ff",dominance:"Bêta",stable:"Bêta",wave:"beta",alpha:33,theta:32,beta:62,essence:"Vous transformez rapidement les objectifs en décisions claires et en actions structurées orientées vers le résultat.",citation:"« La vision sans exécution n'est qu'une hallucination. »",citationAuthor:"Thomas Edison",activite:"Le Décideur présente une dominance marquée de l'onde Bêta, caractérisée par une activation soutenue et stable tout au long de la séance. Les ondes Bêta sont classiquement associées à l'attention dirigée, à la prise de décision, à la planification et à l'exécution de tâches orientées vers un objectif.",perception:"La pensée du Décideur s'organise autour de la hiérarchisation. Face à une situation, l'esprit identifie rapidement ce qui est prioritaire, ce qui est accessoire et ce qui constitue un obstacle. La perception est pragmatique, structurée et directement reliée à la possibilité d'agir.",action:"Dans l'action, le Décideur se distingue par une forte capacité de mise en œuvre. La décision n'est pas une fin en soi, mais une étape vers l'exécution. Une fois l'objectif défini, l'énergie cognitive est mobilisée pour organiser, structurer et maintenir la dynamique.",conditions:"L'efficacité du Décideur est maximale dans des contextes où les objectifs sont clairs, les rôles définis et les responsabilités assumées. Une pression modérée agit comme un facteur stimulant.",role:"Au sein d'un collectif, le Décideur traduit les idées, les orientations et les visions en plans concrets, en étapes opérationnelles et en décisions exécutables.",strengths:"Clarté décisionnelle marquée, efficacité cognitive orientée vers le résultat, forte résistance à la pression.",environments:"Environnements où l'action, la responsabilité et la performance sont valorisées. Management, pilotage de projet, stratégie opérationnelle.",synthese:"Le Décideur incarne un fonctionnement cérébral orienté vers la décision, l'exécution et la progression concrète. Sa force principale réside dans sa capacité à maintenir une dynamique efficace.",compatible:["Le Pilote","L'Éclaireur","Le Guide"],tension:["Le Visionnaire","Le Médiateur"]},
{id:"pilote",name:"Le Pilote",icon:"🎯",color:"#00e5ff",dominance:"Bêta",stable:"Alpha",wave:"beta",alpha:40,theta:20,beta:68,essence:"Vous savez décider et agir vite tout en restant centré, lucide et maître de la situation.",citation:"« Ce n'est pas la force qui fait le commandement, c'est la maîtrise de soi. »",citationAuthor:"Napoléon Bonaparte",activite:"Le Pilote présente une dominance Bêta ponctuée de signaux Alpha, révélant un fonctionnement cérébral orienté vers la décision, la maîtrise et le pilotage dans l'action. Les ondes Bêta traduisent la concentration et la rapidité, tandis que les ondes Alpha apportent calme et stabilité intérieure.",perception:"Le Pilote organise naturellement le réel en priorités et en axes d'action. Il perçoit rapidement ce qui est essentiel et garde la tête froide face à l'incertitude. Son intelligence est une intelligence de pilotage.",action:"Dans l'action, ce profil excelle lorsqu'il est engagé tout en restant centré. Sa force réside dans la précision, la fermeté sans rigidité et la rapidité sans impulsivité.",conditions:"La performance est maximale dans des contextes exigeants où le calme et la rapidité doivent coexister. Les situations de crise maîtrisée favorisent ce profil.",role:"Dans une équipe, le Pilote est le point d'ancrage et le stabilisateur. Il tient la barre quand la situation devient instable et rassure par sa constance.",strengths:"Capacité à conjuguer lucidité et action rapide, sang-froid naturel, leadership calme.",environments:"Environnements de direction, gestion de crise, pilotage opérationnel.",synthese:"Le Pilote incarne un fonctionnement cérébral orienté vers la maîtrise et l'action réfléchie. Il décide sans précipitation et conserve son centre lorsque tout s'accélère.",compatible:["Le Décideur","Le Guide","L'Éclaireur"],tension:["Le Visionnaire","Le Médiateur"]},
{id:"eclaireur",name:"L'Éclaireur",icon:"🔦",color:"#00ff88",dominance:"Bêta",stable:"Thêta",wave:"beta",alpha:28,theta:44,beta:60,essence:"Vous savez décider et agir vite tout en gardant une vision globale et intuitive de la situation.",citation:"« Cela semble toujours impossible, jusqu'à ce qu'on le fasse. »",citationAuthor:"Nelson Mandela",activite:"L'Éclaireur présente une dominance de l'onde Bêta, associée à une stabilité marquée de l'onde Thêta. Les ondes Bêta sont liées à l'engagement actif et à la prise de décision. Les ondes Thêta sont associées aux processus d'intégration, d'intuition et de mise en perspective.",perception:"La perception de l'Éclaireur s'organise autour de deux niveaux : une lecture rapide et concrète de la situation, et une compréhension plus globale intégrant les dimensions humaines et implicites.",action:"Dans l'action, l'Éclaireur avance rapidement tout en ajustant en permanence sa trajectoire. L'énergie bêta favorise l'initiative, tandis que la stabilité thêta permet de maintenir une direction cohérente.",conditions:"La performance est maximale lorsque l'Éclaireur peut alterner de courts temps de recul et des phases d'action soutenue.",role:"Au sein d'un collectif, l'Éclaireur joue un rôle d'orientation dynamique. Il détecte les moments où il faut accélérer ou réajuster et relie l'action immédiate à une vision plus large.",strengths:"Capacité à décider dans des contextes complexes, lecture fine des dynamiques humaines, grande adaptabilité.",environments:"Contextes où la prise d'initiative est valorisée. Pilotage de projets, entrepreneuriat, stratégie, innovation.",synthese:"L'Éclaireur incarne un équilibre entre activation rapide et intégration profonde. Il agit tout en maintenant une vision d'ensemble.",compatible:["Le Décideur","Le Pionnier","Le Pilote"],tension:["Le Médiateur","L'Observateur"]},
{id:"observateur",name:"L'Observateur",icon:"👁️",color:"#ffee00",dominance:"Alpha",stable:"Thêta",wave:"alpha",alpha:68,theta:42,beta:18,essence:"Vous comprenez les situations en profondeur en prenant le temps d'observer, d'intégrer et de laisser émerger une vision globale avant d'agir.",citation:"« Voir ce qui se trouve devant son nez est un combat de tous les instants. »",citationAuthor:"George Orwell",activite:"L'Observateur présente une dominance de l'onde Alpha, associée à une stabilité marquée de l'onde Thêta. Les ondes Alpha sont associées aux états de calme éveillé et de clarté mentale. Les ondes Thêta sont impliquées dans les processus d'intuition et de construction de représentations globales.",perception:"La perception de l'Observateur s'appuie sur une observation posée et continue de l'environnement. L'information est traitée sans urgence, avec une attention portée aux nuances et aux relations entre les éléments.",action:"Dans l'action, l'Observateur privilégie la justesse au rythme. Les décisions émergent après une phase d'intégration interne, lorsque les différents éléments ont trouvé une organisation cohérente.",conditions:"La performance est maximale dans des environnements où le temps d'observation et de réflexion est respecté.",role:"Au sein d'un collectif, l'Observateur occupe un rôle de mise en clarté et de stabilisation. Il aide à prendre du recul et à reformuler les enjeux.",strengths:"Capacité d'écoute, stabilité émotionnelle, lecture fine des dynamiques globales. Aptitude à formuler des synthèses claires.",environments:"Contextes où la réflexion est valorisée, où l'intuition est reconnue. Stratégie, recherche, accompagnement, création.",synthese:"L'Observateur incarne un fonctionnement cérébral fondé sur la stabilité, l'intégration et la vision d'ensemble. Il transforme le calme en clarté.",compatible:["Le Médiateur","Le Chef d'Orchestre","Le Guide"],tension:["L'Éclaireur","Le Pionnier"]},
{id:"guide",name:"Le Guide",icon:"🧭",color:"#ff88aa",dominance:"Alpha",stable:"Bêta",wave:"alpha",alpha:60,theta:22,beta:48,essence:"Vous prenez des décisions claires et efficaces en restant calme, structuré et parfaitement centré sur les priorités.",citation:"« Peu importe la rapidité avec laquelle vous courez, si vous êtes sur la mauvaise route, vous n'arriverez nulle part. »",citationAuthor:"Warren Buffett",activite:"Le Guide présente une dominance de l'onde Alpha, associée à une stabilité marquée de l'onde Bêta. Les ondes Alpha sont liées aux états de calme éveillé et de clarté cognitive. Les ondes Bêta sont associées à l'engagement et à la prise de décision.",perception:"La perception du Guide s'appuie d'abord sur une évaluation calme et structurée des situations. L'information est intégrée de manière globale, avec une attention portée à la cohérence et aux priorités.",action:"Dans l'action, le Guide se distingue par sa capacité à transformer la clarté intérieure en décisions concrètes. Il agit rarement dans la précipitation.",conditions:"La performance est maximale dans des contextes où il est nécessaire de combiner analyse, sang-froid et réactivité.",role:"Au sein d'un collectif, le Guide joue un rôle de structuration et de décision. Il contribue à clarifier les options et à transformer la réflexion collective en plan d'action.",strengths:"Clarté mentale, capacité à hiérarchiser, sang-froid, aptitude à engager l'action de manière ciblée et durable.",environments:"Contextes où la prise de décision structurée est essentielle. Management, direction de projet, coordination d'équipes.",synthese:"Le Guide incarne un fonctionnement cérébral fondé sur la stabilité, la clarté et l'engagement ciblé. Il transforme le calme en capacité de décision.",compatible:["Le Pilote","L'Observateur","Le Décideur"],tension:["Le Visionnaire","Le Pionnier"]},
{id:"chef_orchestre",name:"Le Chef d'Orchestre",icon:"🎼",color:"#ff3366",dominance:"Alpha",stable:"Alpha",wave:"alpha",alpha:74,theta:30,beta:25,essence:"Vous harmonisez les dynamiques et empêchez les excès, émotionnels comme décisionnels.",citation:"« L'harmonie, c'est l'équilibre ; et l'équilibre, c'est l'ordre. »",citationAuthor:"Victor Hugo",activite:"Le Chef d'Orchestre présente une dominance de l'onde Alpha, à la fois en termes de variation d'intensité et de stabilité sur l'ensemble de la séance. Les ondes Alpha sont associées aux états de calme éveillé, de régulation émotionnelle et de stabilité cognitive.",perception:"Le Chef d'Orchestre perçoit les situations avec calme et continuité. L'information est traitée sans précipitation, avec une attention portée à la cohérence et à l'équilibre global.",action:"Dans l'action, le Chef d'Orchestre se distingue par sa constance et sa fiabilité. Les décisions sont prises sans précipitation. L'engagement n'est pas fondé sur l'intensité, mais sur la durée.",conditions:"La performance est maximale dans des environnements où la pression émotionnelle est forte ou lorsque la continuité est essentielle.",role:"Au sein d'un collectif, le Chef d'Orchestre occupe un rôle de stabilisation et de cohésion. Il contribue à apaiser les tensions et à maintenir un climat propice à la coopération.",strengths:"Grande stabilité émotionnelle, fiabilité dans le temps, capacité d'écoute, sens de la cohérence.",environments:"Contextes où la relation, la transmission et la coopération sont centrales. Accompagnement, enseignement, management humain, médiation.",synthese:"Le Chef d'Orchestre incarne un fonctionnement cérébral fondé sur la régulation, la continuité et la cohérence. Il offre un point d'ancrage fiable autour duquel l'action peut s'organiser dans le temps.",compatible:["L'Observateur","Le Médiateur","Le Guide"],tension:["Le Pionnier","L'Éclaireur"]}
];
const tabRow=document.getElementById('tabRow'),pw=document.getElementById('pw');
let activeIdx=0;const auraInited=new Set();
PERSONAS.forEach((p,idx)=>{
const tab=document.createElement('div');
tab.className='tab visible';tab.dataset.idx=idx;tab.dataset.wave=p.wave;
tab.textContent=p.icon+' '+p.name;
tab.addEventListener('click',()=>switchTo(idx));
tabRow.appendChild(tab);
const aId='aura_'+p.id;
const compat=p.compatible.map(n=>`<div class="badge" style="border-color:${p.color}33;color:${p.color}" data-name="${n}">${n}</div>`).join('');
const tens=p.tension.length?`<div class="compat-lbl" style="color:rgba(255,80,80,.6);border-color:rgba(255,80,80,.15);margin-top:1.5rem">⚠️ Tensions cognitives possibles</div><div class="badges">${p.tension.map(n=>`<div class="badge" style="border-color:rgba(255,80,80,.25);color:rgba(255,80,80,.7)">${n}</div>`).join('')}</div>`:'';
const div=document.createElement('div');
div.className='pd'+(idx===0?' active':'');
div.innerHTML=`
<div class="pd-hero reveal">
<div style="position:absolute;inset:0;background:radial-gradient(ellipse 60% 100% at 0 50%,${p.color}06,transparent 65%);pointer-events:none"></div>
<div style="position:relative">
<div class="pd-tag" style="color:${p.color}">${p.dominance} dominant — Stabilité ${p.stable}</div>
<div class="pd-title">${p.icon} ${p.name}</div>
<span class="pd-sub">Dominance ${p.dominance} — Stabilité ${p.stable}</span>
<p class="pd-essence">${p.essence}</p>
</div>
<div class="pd-vis">
<div class="pd-aura"><canvas id="${aId}" width="160" height="160"></canvas></div>
<div class="pd-bars">
<div class="bar-row"><span class="bar-lbl" style="color:#00e5ff">α</span><div class="bar-track"><div class="bar-fill" style="width:${p.alpha}%;background:#00e5ff"></div></div></div>
<div class="bar-row"><span class="bar-lbl" style="color:#ff9500">θ</span><div class="bar-track"><div class="bar-fill" style="width:${p.theta}%;background:#ff9500"></div></div></div>
<div class="bar-row"><span class="bar-lbl" style="color:#4488ff">β</span><div class="bar-track"><div class="bar-fill" style="width:${p.beta}%;background:#4488ff"></div></div></div>
</div>
</div>
</div>
<div class="pd-quote reveal d1" style="border-color:${p.color}">${p.citation}<span>— ${p.citationAuthor}</span></div>
<div class="pd-sec reveal d1"><div class="sec-lbl" style="color:${p.color}">🧠 Activité cérébrale observée</div><p>${p.activite}</p></div>
<div class="pd-sec reveal d1"><div class="sec-lbl" style="color:${p.color}">👁️ Mode de perception et de pensée</div><p>${p.perception}</p></div>
<div class="pd-sec reveal d2"><div class="sec-lbl" style="color:${p.color}">⚡ Fonctionnement dans l'action</div><p>${p.action}</p></div>
<div class="pd-sec reveal d2"><div class="sec-lbl" style="color:${p.color}">✨ Conditions de performance optimale</div><p>${p.conditions}</p></div>
<div class="pd-sec reveal d3"><div class="sec-lbl" style="color:${p.color}">👥 Rôle naturel au sein d'un groupe</div><p>${p.role}</p></div>
<div class="pd-2col">
<div class="pd-sec reveal d3"><div class="sec-lbl" style="color:#00ff88">💪 Points forts</div><p>${p.strengths}</p></div>
<div class="pd-sec reveal d4"><div class="sec-lbl" style="color:#ff9500">🌍 Environnements favorables</div><p>${p.environments}</p></div>
</div>
<div class="pd-compat reveal d4"><div class="compat-lbl">✅ Compatibilités naturelles</div><div class="badges">${compat}</div>${tens}</div>
<div class="pd-synth reveal d4"><div class="sec-lbl" style="color:${p.color}">📋 Synthèse du profil</div><p style="font-weight:300;font-size:.9rem;line-height:1.85;color:rgba(240,238,255,.8)">${p.synthese}</p></div>`;
pw.appendChild(div);
});
document.addEventListener('click',e=>{
if(e.target.dataset.name){const nm=e.target.dataset.name;const idx=PERSONAS.findIndex(p=>p.name===nm||p.name.replace(/['']/g,"'")===nm.replace(/['']/g,"'"));if(idx>=0)switchTo(idx);}
});
function switchTo(idx){
activeIdx=idx;const p=PERSONAS[idx];
document.querySelectorAll('.tab').forEach((t,i)=>{
if(i===idx){t.classList.add('active');t.style.borderTopColor=PERSONAS[i].color;t.style.background=PERSONAS[i].color+'22';t.style.color=PERSONAS[i].color;}
else{t.classList.remove('active');t.style.borderTopColor='transparent';t.style.background='';t.style.color='';}
});
document.querySelectorAll('.pd').forEach((d,i)=>d.classList.toggle('active',i===idx));
if(!auraInited.has(p.id)){auraInited.add(p.id);initAura(document.getElementById('aura_'+p.id),p.color);}
document.querySelectorAll('.pd.active .reveal').forEach(el=>{el.classList.remove('visible');setTimeout(()=>el.classList.add('visible'),50);});
window.scrollTo({top:document.getElementById('tabRow').offsetTop-80,behavior:'smooth'});
cur.style.background=p.color;
}
document.querySelectorAll('.wn').forEach(btn=>{
btn.addEventListener('click',()=>{
document.querySelectorAll('.wn').forEach(b=>b.classList.remove('active'));
btn.classList.add('active');const wave=btn.dataset.wave;
document.querySelectorAll('.tab').forEach((t,i)=>{t.classList.toggle('visible',wave==='all'||PERSONAS[i].wave===wave);});
if(wave!=='all'){const fi=PERSONAS.findIndex(p=>p.wave===wave);if(fi>=0&&PERSONAS[activeIdx].wave!==wave)switchTo(fi);}
});
});
switchTo(0);
function initAura(canvas,color){
if(!canvas)return;
const ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height;
const sec=color==='#00e5ff'?'#00ff88':color==='#ff3366'?'#ff9500':color==='#ffee00'?'#ff9500':'#00e5ff';
const pts=[];
class P{constructor(){this.reset()}reset(){this.x=W/2+(Math.random()-.5)*10;this.y=H/2+(Math.random()-.5)*10;this.vx=(Math.random()-.5)*1.2;this.vy=(Math.random()-.5)*1.2;this.c=Math.random()>.55?color:sec;this.a=Math.random()*.5+.2;this.life=0;this.max=90+Math.random()*70;this.h=[];this.mh=26;}update(t){const a=Math.sin(this.x*.013+t)*Math.PI*2;this.vx+=Math.cos(a)*.09;this.vy+=Math.sin(a)*.09;const sp=Math.sqrt(this.vx**2+this.vy**2);if(sp>1.7){this.vx/=sp/1.7;this.vy/=sp/1.7;}this.x+=this.vx;this.y+=this.vy;this.h.push({x:this.x,y:this.y});if(this.h.length>this.mh)this.h.shift();this.life++;if(this.life>this.max||this.x<0||this.x>W||this.y<0||this.y>H)this.reset();}draw(){if(this.h.length<2)return;ctx.beginPath();ctx.moveTo(this.h[0].x,this.h[0].y);this.h.forEach(p=>ctx.lineTo(p.x,p.y));ctx.strokeStyle=this.c;ctx.globalAlpha=this.a*Math.min(this.life/10,1)*Math.min((this.max-this.life)/16,1);ctx.lineWidth=.8;ctx.shadowBlur=5;ctx.shadowColor=this.c;ctx.stroke();ctx.globalAlpha=1;ctx.shadowBlur=0;}}
for(let i=0;i<55;i++){const p=new P();p.life=Math.floor(Math.random()*p.max);pts.push(p);}
let t=0;function anim(){ctx.fillStyle='rgba(0,0,5,.18)';ctx.fillRect(0,0,W,H);t+=.035;pts.forEach(p=>{p.update(t);p.draw();});requestAnimationFrame(anim);}anim();
}
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible');}),{threshold:.08});
document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));